config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root 'pages#index'

  namespace :api do
    namespace :v1 do
      resources :reviews, only: [:create, :destroy]
      #resources :trail_images
      resources :trails, param: :slug
      resources :users
    end
  end

  # once we use react router, it allows us to handle routing to our react component
  # without messing up ruby api routing
  get '*path', to: 'pages#index', via: :all

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  
end

app/models/trail.rb
class Trail < ApplicationRecord
  has_many :reviews
  has_many :trail_images, dependent: :destroy  # This is crucial!

  before_create :slugify
  before_validation :slugify, if: :name_changed?

  def slugify
    self.slug = name.parameterize
  end
  
  def avg_score
    reviews.average(:rating).round(2).to_f
  end
end

app/controllers/api/v1/trails_controller.rb
module Api
  module V1
    class TrailsController < ApplicationController
      protect_from_forgery with: :null_session
      before_action :set_trail, only: %i[ show edit update destroy ]

      # GET /trails or /trails.json
      def index
        @trails = Trail.all

        render json: TrailSerializer.new(@trails, options).serialized_json
      end

      # GET /trails/1 or /trails/1.json (boilerplate)
      # in this case, now its trails/slug-name
      def show
        @trail = Trail.find_by(slug: params[:slug])

        render json: TrailSerializer.new(@trail, options).serialized_json
      end

      # GET /trails/new
      def new
        @trail = Trail.new
      end

      # GET /trails/1/edit
      def edit
      end

      # POST /trails or /trails.json
      # def create
      #   @trail = Trail.new(trail_params)

      #   respond_to do |format|
      #     if @trail.save
      #       format.html { redirect_to @trail, notice: "Trail was successfully created." }
      #       format.json { render :show, status: :created, location: @trail }
      #     else
      #       format.html { render :new, status: :unprocessable_entity }
      #       format.json { render json: @trail.errors, status: :unprocessable_entity }
      #     end
      #   end
      # end
      def create
        @trail = Trail.new(trail_params)

        if @trail.save
          render json: TrailSerializer.new(@trail).serializable_hash, status: :created # Serialize with fast_jsonapi
        else
          render json: @trail.errors, status: :unprocessable_entity #Handle with frontend
        end
      end

      # PATCH/PUT /trails/1 or /trails/1.json
      def update
        if @trail.update(trail_params)
          # format.html { redirect_to @trail, notice: "Trail was successfully updated." }
          # format.json { render :show, status: :ok, location: @trail }
          render json: TrailSerializer.new(@trail, options).serializable_hash, status: :created # Serialize with fast_jsonapi
        else
          # format.html { render :edit, status: :unprocessable_entity }
          # format.json { render json: @trail.errors, status: :unprocessable_entity }
          render json: @trail.errors, status: :unprocessable_entity #Handle with frontend
        end
      end

      # DELETE /trails/1 or /trails/1.json
      def destroy
        if @trail.destroy!
          head :no_content
        else
          render json: @trail.errors, status: :unprocessable_entity #Handle with frontend

        # respond_to do |format|
        #   format.html { redirect_to trails_path, status: :see_other, notice: "Trail was successfully destroyed." }
        #   format.json { head :no_content }
        end
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_trail
          #@trail = Trail.find(params.expect(:id)) (boilerplate, should i use this?)
          @trail = Trail.find_by(slug: params[:slug])
        end

        # Only allow a list of trusted parameters through.
        def trail_params
          params.expect(trail: [ :name, :description, :difficulty, :length, :elevation_gain, :route_type, :latitude, :longitude, :address, :city, :state, :country, :zip_code, :average_rating, :image_url, :park_id ])
        end

        # compound response, returns "included" section with other model types that belong to it
        # i.e, reviews
        def options
          @options ||= { include: %i[reviews] }
        end
    end
  end
end

app/helpers/trails_helper.rb
module TrailsHelper
end

app/views/trails/_form.html.erb
<%= form_with(model: trail) do |form| %>
  <% if trail.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(trail.errors.count, "error") %> prohibited this trail from being saved:</h2>

      <ul>
        <% trail.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.textarea :description %>
  </div>

  <div>
    <%= form.label :difficulty, style: "display: block" %>
    <%= form.number_field :difficulty %>
  </div>

  <div>
    <%= form.label :length, style: "display: block" %>
    <%= form.text_field :length %>
  </div>

  <div>
    <%= form.label :elevation_gain, style: "display: block" %>
    <%= form.number_field :elevation_gain %>
  </div>

  <div>
    <%= form.label :route_type, style: "display: block" %>
    <%= form.number_field :route_type %>
  </div>

  <div>
    <%= form.label :latitude, style: "display: block" %>
    <%= form.text_field :latitude %>
  </div>

  <div>
    <%= form.label :longitude, style: "display: block" %>
    <%= form.text_field :longitude %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :state, style: "display: block" %>
    <%= form.text_field :state %>
  </div>

  <div>
    <%= form.label :country, style: "display: block" %>
    <%= form.text_field :country %>
  </div>

  <div>
    <%= form.label :zip_code, style: "display: block" %>
    <%= form.text_field :zip_code %>
  </div>

  <div>
    <%= form.label :average_rating, style: "display: block" %>
    <%= form.text_field :average_rating %>
  </div>

  <div>
    <%= form.label :image_url, style: "display: block" %>
    <%= form.text_field :image_url %>
  </div>

  <div>
    <%= form.label :park_id, style: "display: block" %>
    <%= form.number_field :park_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/trails/_trail.html.erb
<div id="<%= dom_id trail %>">
  <p>
    <strong>Name:</strong>
    <%= trail.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= trail.description %>
  </p>

  <p>
    <strong>Difficulty:</strong>
    <%= trail.difficulty %>
  </p>

  <p>
    <strong>Length:</strong>
    <%= trail.length %>
  </p>

  <p>
    <strong>Elevation gain:</strong>
    <%= trail.elevation_gain %>
  </p>

  <p>
    <strong>Route type:</strong>
    <%= trail.route_type %>
  </p>

  <p>
    <strong>Latitude:</strong>
    <%= trail.latitude %>
  </p>

  <p>
    <strong>Longitude:</strong>
    <%= trail.longitude %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= trail.address %>
  </p>

  <p>
    <strong>City:</strong>
    <%= trail.city %>
  </p>

  <p>
    <strong>State:</strong>
    <%= trail.state %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= trail.country %>
  </p>

  <p>
    <strong>Zip code:</strong>
    <%= trail.zip_code %>
  </p>

  <p>
    <strong>Average rating:</strong>
    <%= trail.average_rating %>
  </p>

  <p>
    <strong>Image url:</strong>
    <%= trail.image_url %>
  </p>
  
  <p>
    <strong>Park:</strong>
    <%= trail.park_id %>
  </p>

</div>

app/views/trails/edit.html.erb
<% content_for :title, "Editing trail" %>

<h1>Editing trail</h1>

<%= render "form", trail: @trail %>

<br>

<div>
  <%= link_to "Show this trail", @trail %> |
  <%= link_to "Back to trails", trails_path %>
</div>

app/views/trails/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Trails" %>

<h1>Trails</h1>

<div id="trails">
  <% @trails.each do |trail| %>
    <%= render trail %>
    <p>
      <%= link_to "Show this trail", trail %>
    </p>
  <% end %>
</div>

<%= link_to "New trail", new_trail_path %>

app/views/trails/new.html.erb
<% content_for :title, "New trail" %>

<h1>New trail</h1>

<%= render "form", trail: @trail %>

<br>

<div>
  <%= link_to "Back to trails", trails_path %>
</div>

app/views/trails/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @trail %>

<div>
  <%= link_to "Edit this trail", edit_trail_path(@trail) %> |
  <%= link_to "Back to trails", trails_path %>

  <%= button_to "Destroy this trail", @trail, method: :delete %>
</div>