config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root 'pages#index'

  namespace :api do
    namespace :v1 do
      resources :reviews, only: [:create, :destroy]
      #resources :trail_images
      resources :trails, param: :slug
      resources :users
    end
  end

  # once we use react router, it allows us to handle routing to our react component
  # without messing up ruby api routing
  get '*path', to: 'pages#index', via: :all

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  
end

app/controllers/api/v1/reviews_controller.rb
module Api
  module V1
    class ReviewsController < ApplicationController
      protect_from_forgery with: :null_session
      before_action :set_review, only: %i[ destroy ]

      # GET /reviews or /reviews.json
      # def index
      #   @reviews = Review.all
      # end

      # GET /reviews/1 or /reviews/1.json
      # def show
      #   render json: ReviewSerializer.new(review).serialized_json
      # end

      # GET /reviews/new
      # def new
      #   @review = Review.new
      # end

      # GET /reviews/1/edit
      # def edit
      # end

      # POST /reviews or /reviews.json
      def create
        @review = Review.new(review_params)

        if @review.save
          render json: ReviewSerializer.new(@review).serializable_hash, status: :created # Serialize with fast_jsonapi
        else
          render json: @review.errors, status: :unprocessable_entity #Handle with frontend
        end
        # respond_to do |format|
        #   if @review.save
        #     format.html { redirect_to @review, notice: "Review was successfully created." }
        #     format.json { render :show, status: :created, location: @review }
        #   else
        #     format.html { render :new, status: :unprocessable_entity }
        #     format.json { render json: @review.errors, status: :unprocessable_entity }
        #   end
        # end
      end

      # PATCH/PUT /reviews/1 or /reviews/1.json
      # def update
      #   respond_to do |format|
      #     if @review.update(review_params)
      #       format.html { redirect_to @review, notice: "Review was successfully updated." }
      #       format.json { render :show, status: :ok, location: @review }
      #     else
      #       format.html { render :edit, status: :unprocessable_entity }
      #       format.json { render json: @review.errors, status: :unprocessable_entity }
      #     end
      #   end
      # end

      # DELETE /reviews/1 or /reviews/1.json
      def destroy
        if @review.destroy!
          head :no_content
        else
          render json: @review.errors, status: :unprocessable_entity #Handle with frontend
        end
        # @review.destroy!

        # respond_to do |format|
        #   format.html { redirect_to reviews_path, status: :see_other, notice: "Review was successfully destroyed." }
        #   format.json { head :no_content }
        # end
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_review
          @review = Review.find(params.expect(:id))
        end

        # Only allow a list of trusted parameters through.
        def review_params
          params.expect(review: [ :rating, :comment, :user_id, :trail_id, :date ])
        end
    end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_with(model: review) do |form| %>
  <% if review.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
        <% review.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :rating, style: "display: block" %>
    <%= form.number_field :rating %>
  </div>

  <div>
    <%= form.label :comment, style: "display: block" %>
    <%= form.textarea :comment %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :trail_id, style: "display: block" %>
    <%= form.text_field :trail_id %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/_review.html.erb
<div id="<%= dom_id review %>">
  <p>
    <strong>Rating:</strong>
    <%= review.rating %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= review.comment %>
  </p>

  <p>
    <strong>User:</strong>
    <%= review.user_id %>
  </p>

  <p>
    <strong>Trail:</strong>
    <%= review.trail_id %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= review.date %>
  </p>

</div>

app/views/reviews/edit.html.erb
<% content_for :title, "Editing review" %>

<h1>Editing review</h1>

<%= render "form", review: @review %>

<br>

<div>
  <%= link_to "Show this review", @review %> |
  <%= link_to "Back to reviews", reviews_path %>
</div>

app/views/reviews/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Reviews" %>

<h1>Reviews</h1>

<div id="reviews">
  <% @reviews.each do |review| %>
    <%= render review %>
    <p>
      <%= link_to "Show this review", review %>
    </p>
  <% end %>
</div>

<%= link_to "New review", new_review_path %>

app/views/reviews/new.html.erb
<% content_for :title, "New review" %>

<h1>New review</h1>

<%= render "form", review: @review %>

<br>

<div>
  <%= link_to "Back to reviews", reviews_path %>
</div>

app/views/reviews/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @review %>

<div>
  <%= link_to "Edit this review", edit_review_path(@review) %> |
  <%= link_to "Back to reviews", reviews_path %>

  <%= button_to "Destroy this review", @review, method: :delete %>
</div>